stages:
  - build
  - test
  - deploy

before_script:
  - ruby -v
  - which ruby

generate_asciidoc:
  stage: build
  tags:
    - ruby
  script:
    - gem install asciidoctor
    - ./generate_adoc_html.sh
  artifacts:
    paths:
      - Oracle_performance_analysis_with_Panorama_from_adoc.html
      - images/

generate_content:
  stage: build
  tags:
    - ruby
  script:
    - ./generate_content.sh
  artifacts:
    paths:
      - panorama_content_generated.html