# GitHub action recipe
name: Generate content

on:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string, runs on Sunday morning
   # - cron: '0 0 * * 0'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate with asciidoctor
        run: |
          export GEM_PATH=$PWD
          gem install --install-dir . asciidoctor
          find . -name asciidoctor
          ./bin/asciidoctor -o Oracle_performance_analysis_with_Panorama.html Oracle_performance_analysis_with_Panorama.adoc
          ls -l 
          run: git remote set-url origin ${{ secrets.ssh }}
          git status
          # git add .
          # git commit -m "Auto updating TODO.txt"
          # git fetch origin master
          # git push origin HEAD:master

 


