# GitHub action recipe
name: Generate content

on:
  push:
  #schedule:
    # * is a special character in YAML so you have to quote this string, runs on Sunday morning
   # - cron: '0 0 * * 0'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate with asciidoctor
        run: |
          export GEM_PATH=$PWD
          gem install --install-dir . asciidoctor
          find . -name asciidoctor
          ./bin/asciidoctor -o Oracle_performance_analysis_with_Panorama.html Oracle_performance_analysis_with_Panorama.adoc
      - name: git config
        run: |
          git config user.email "Peter@ramm-oberhermsdorf.de"
          git config user.name "Peter Ramm"
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: git status
        run: git status
      - name: git stage
        run: git stage Oracle_performance_analysis_with_Panorama.html
      - name: git commit
        run: git commit -m "Auto generating Oracle_performance_analysis_with_Panorama.html"
      - name: git fetch
        run: git fetch origin master
      - name: git push
        run: git push origin HEAD:master

 


